name: Deploy App $APP $STAGE

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      stage:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      appName:
        description: "App Name(package.json 참조)"
        required: true
        type: choice
        options:
          - epick
          - collection-detail
          - storepick
          - store-pick-banner
          - benefit
      stage:
        description: "Stage Name"
        required: true
        type: choice
        default: alpha
        options:
          - alpha
          - beta
          - production

jobs:
  artifact_upload:
    name: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo >> APP.txt
      - name: Upload APP_NAME
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.appName || github.event.inputs.appName }}
          path: APP.txt
      - shell: bash
        run: echo >> STAGE.txt
      - name: Upload STAGE_NAME
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.appName || github.event.inputs.appName }}
          path: STAGE.txt
