name: Deploy App $APP $STAGE

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "App Name(package.json 참조)"
        required: true
        type: choice
        options:
          - epick
          - collection-detail
          - storepick
          - store-pick-banner
          - benefit
      stage:
        description: "Stage Name"
        required: true
        type: choice
        default: alpha
        options:
          - alpha
          - beta
          - production

env:
  APP: ${{ github.event.inputs.appName }}
  STAGE: ${{ github.event.inputs.stage }}

jobs:
  artifact_upload:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo $APP >> APP_NAME.text
          echo $STAGE >> STAGE_NAME.txt
      - name: Upload APP_NAME
        uses: actions/upload-artifact@v2
        with:
          name: APP_NAME
          path: APP_NAME.text

      - name: Upload STAGE_NAME
        uses: actions/upload-artifact@v2
        with:
          name: STAGE_NAME
          path: STAGE_NAME.text
