name: epick alpha

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: lebmouse/test-badge-action/.github/workflows/badge-test.yml
        with:
          appName: epick
          stage: alpha
