name: epick alpha

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: ./.github/workflows/badge-test.yml
        with:
          appName: epick
          stage: alpha
